### PR TITLE
#9 Add Calamari branding

### PR DESCRIPTION
**Pull request by nickavv**
logo

### CODE REVIEW

**Review by romeara — COMMENTED** [review]
Looks cool, but my two maybe-change-this thoughts:
1) First thought when I saw it was "trogdor beefy tentacle arm"
2) Maybe not purple?

**Comment by nickavv** [comment]
image
Some new color choices, also added "sucker" spots to the top one so tell me if you think those are good?

**Comment by romeara** [comment]
@nickavv  I like the sucker-spot detailing. Not sure on which color, what do you think?

**Comment by nickavv** [comment]
I think the green is my favorite, now with sucker shading:
image

Thoughts?

**Comment by romeara** [comment]
@nickavv I like it, forrwwwaaaaarrrdddd!

**Pull request merged**
